version: '3'
services:
  web:
    build: ./main_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
  phi2:
    build: ./phi2_model
    ports:
      - "5001:5000"
    volumes:
      - ./phi2_model:/app
    environment:
      FLASK_ENV: development
